### PR TITLE
[1.4] Tile "smart interact" fixes/additions, sitting

### LINKED ISSUE #2050: [1.4] Highlight outlines for modded furniture doesn't show
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

The highlight outline from using smart cursor on modded tiles that have one don't show the outline, nor does the smart cursor detect the tile. Seems to be the case with all my modded deco that would have it, and TileID.Sets.HasOutlines is set to true and the _Highlight sprite does exist.

### Log File

_No response_

### Steps to reproduce

_No response_

### Expected Behavior

_No response_

### Actual Behavior

_No response_

### Reproduction frequency

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by direwolf420**
# Bug
### What is the bug?
Fixes #2050.

### Porting for modders
Not breaking: `ModTile.HasSmartInteract` now has `int i, int j, Terraria.GameContent.ObjectInteractions.SmartInteractScanSettings settings` as parameters

### How did you fix the bug?
Reimplement `ModTile.HasSmartInteract` and related hooks.

### Are there alternatives to your fix?
No. See Additions for details.

# Additions
### What are the additions?
Several things related to highlights and smart interactions are added/updated:

* Updated `ExampleChair` implementation based on 1.4 changes, added `ExampleToilet` (both almost the same functionality).
* `ExampleChair` now has a highlight texture.
* Added new parameters to `HasSmartInteract` which are used for conditional checks like vanilla, showcased in `ExampleToilet`.
* Added new `ModTile.ModifySmartInteractCoords` hook which is showcased for `ExampleBed`, `ExampleChair`, and `ExampleToilet`, and should also be showcased whenever `ExampleDresser` gets ported.
* Added new `ModTile.ModifySittingTargetInfo` hook which is showcased for `ExampleChair` and `ExampleToilet`.
* Added new `ModTile.ModifySleepingTargetInfo` hook which is showcased for `ExampleBed`.
* Added new `TileRestingInfo` struct which is used as a parameter in the above two hooks.
* Changed the NPC sitting code to account for modded chairs. **How to test it:** Put an NPC inside a valid house (table + chair + light source + closed off + walls, set game to nighttime. That will automatically force them to seek the nearest chair and sit on it)
* Added `NPC.SitDown` helper method as the code was reused two times.
* Added `NPCID.Sets.CannotSitOnFurniture`.
* `ExampleBed` and `ExampleChair` sprites have been slightly changed to accomodate for 1.4 sprites and code.

#### Vanilla changes
There were some small vanilla changes required to facilitate NPCs sitting on modded furniture: The chair searching loop was adjusted to remove the hardcoded framing checks, and the iterations doubled (by removing the hardcoded checks for 2 tile high chairs).
To make it easier on modders (and calling the hooks on tmls side), I decided to force the hook to be called on the bottom-most tile for vanilla tiles in _all contexts_ (not just the player one like it originally does), and arbitrary ones for modded (as this information is not available before calling the hook), this makes it much clearer to follow the logic as it's now unified. The downside is that the hardcode from vanilla (offset for 2 tile high chairs) is a slight maintenance overhead. If vanilla decides to add 3 or 1 tile high chairs for example, the code will change to support them on vanillas side, so these adjustments can be removed if need be.

### Are there any alternatives to your implementation?
* I mirrored vanilla as much as possible regarding the new hooks. I also removed `extraX` from `ModTile.ModifySmartInteractCoords` because it was unused (both 1.3 and 1.4), maybe since now a hook exists, it should be added back?
* The bed hooks are not affected by those vanilla changes, as the offsets apply to modded ones directly. Remarked in `ExampleBed` to avoid confusion.

### CODE REVIEW

File: ExampleMod/Content/Tiles/ExampleHerb.cs [hunk 1]
```diff
@@ -96,11 +101,16 @@ public class ExampleHerb : ModTile
 		}
 
 		public override void SetSpriteEffects(int i, int j, ref SpriteEffects spriteEffects) {
-			if (i % 2 == 1) {
+			if (i % 2 == 0) {
 				spriteEffects = SpriteEffects.FlipHorizontally;
 			}
 		}
 
+		public override void SetDrawPositions(int i, int j, ref int width, ref int offsetY, ref int height, ref short tileFrameX, ref short tileFrameY) {
```
Comment (JavidPack) [inline ExampleMod/Content/Tiles/ExampleHerb.cs:109]: This seems unnecessary, height is already 20 and offsetY is already -1 from StyleAlch

File: ExampleMod/Content/Tiles/Furniture/ExampleBed.cs [hunk 2]
```diff
@@ -16,16 +18,20 @@ public class ExampleBed : ModTile
 			Main.tileFrameImportant[Type] = true;
 			Main.tileLavaDeath[Type] = true;
 			TileID.Sets.HasOutlines[Type] = true;
-			TileID.Sets.CanBeSleptIn[Type] = true;
+			TileID.Sets.CanBeSleptIn[Type] = true; // Facilitates calling ModifySleepingTargetInfo
+			TileID.Sets.InteractibleByNPCs[Type] = true;
 			TileID.Sets.IsValidSpawnPoint[Type] = true;
 			TileID.Sets.DisableSmartCursor[Type] = true;
 
+			AddToArray(ref TileID.Sets.RoomNeeds.CountsAsChair);
```
Comment (JavidPack) [inline ExampleMod/Content/Tiles/Furniture/ExampleBed.cs]: We need a comment here clarifying why beds count as chairs I think. InteractibleByNPCs also

File: ExampleMod/Content/Tiles/Furniture/ExampleBed.cs [hunk 3]
```diff
@@ -34,10 +40,27 @@ public class ExampleBed : ModTile
...
 
+		public override void ModifySmartInteractCoords(ref int width, ref int height, ref int frameWidth, ref int frameHeight, ref int extraY) {
+			// Because beds have special smart interaction, this splits up the left and right side into the necessary 2x2 sections
+			width = 2; // Default to the Width defined for TileObjectData.newTile
+			height = 2; // Default to the Height defined for TileObjectData.newTile
+			extraY = 0; // Depends on how you set up frameHeight and CoordinateHeights and CoordinatePaddingFix.Y
+		}
+
+		public override void SetDrawPositions(int i, int j, ref int width, ref int offsetY, ref int height, ref short tileFrameX, ref short tileFrameY) {
+			height = 18; // Set frame height independent of CoordinateHeights
```
Comment (JavidPack) [inline ExampleMod/Content/Tiles/Furniture/ExampleBed.cs]: This is already handled by CoordinateHeights, right? This doesn't seem to do anything.

File: ExampleMod/Content/Tiles/Furniture/ExampleChair.cs [hunk 4]
```diff
@@ -48,5 +57,67 @@ public class ExampleChair : ModTile
...
+			return settings.player.IsWithinSnappngRangeToTile(i, j, PlayerSittingHelper.ChairSittingMaxDistance); // Avoid being able to trigger it from long range
+		}
+
+		public override void ModifySmartInteractCoords(ref int width, ref int height, ref int frameWidth, ref int frameHeight, ref int extraY) {
+			// See ExampleBed tile for explanation
+			extraY = 4;
+		}
+
+		public override void SetDrawPositions(int i, int j, ref int width, ref int offsetY, ref int height, ref short tileFrameX, ref short tileFrameY) {
+			if (tileFrameY % NextStyleHeight == 18) {
```
Comment (JavidPack) [inline ExampleMod/Content/Tiles/Furniture/ExampleChair.cs]: Same as the others, already handled by TileObjectData

File: ExampleMod/Content/Tiles/Furniture/ExampleChair.cs [hunk 5]
```diff
@@ -48,5 +57,67 @@ public class ExampleChair : ModTile
...
 			Item.NewItem(new EntitySource_TileBreak(i, j), i * 16, j * 16, 16, 32, ModContent.ItemType<Items.Placeable.Furniture.ExampleChair>());
 		}
+
+		public override bool HasSmartInteract(int i, int j, SmartInteractScanSettings settings) {
+			return settings.player.IsWithinSnappngRangeToTile(i, j, PlayerSittingHelper.ChairSittingMaxDistance); // Avoid being able to trigger it from long range
+		}
+
+		public override void ModifySmartInteractCoords(ref int width, ref int height, ref int frameWidth, ref int frameHeight, ref int extraY) {
+			// See ExampleBed tile for explanation
+			extraY = 4;
```
Comment (JavidPack) [inline ExampleMod/Content/Tiles/Furniture/ExampleChair.cs]: Same here, this value is already accounted for.

File: patches/tModLoader/Terraria/DataStructures/TileRestingInfo.cs [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+	{
+		/// <summary>
+		/// The resting entity (Player or NPC). Can be null if not available from the context.
+		/// </summary>
+		public Entity restingEntity;
+
+		/// <summary>
+		/// The bottom-most position of the resting tile in tile coordinates, affecting logic for resetting (invalid) resting state and used to align the hitbox.
+		/// </summary>
+		public Point anchorTilePosition;
```
Comment (JavidPack) [inline patches/tModLoader/Terraria/DataStructures/TileRestingInfo.cs:18]: We should reiterate that this is in tile coordinates

File: patches/tModLoader/Terraria/DataStructures/TileRestingInfo.cs [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+
+		/// <summary>
+		/// The visual offset, not affecting any logic.
+		/// </summary>
+		public Vector2 visualOffset;
```
Comment (JavidPack) [inline patches/tModLoader/Terraria/DataStructures/TileRestingInfo.cs:23]: Clarify that this is the visual offset of the entity

File: patches/tModLoader/Terraria/ID/NPCID.TML.cs [hunk 8]
```diff
@@ -26,6 +26,12 @@ public static partial class Sets
 			/// True will force a name to be rolled regardless of vanilla behavior. False will have vanilla handle the naming.
 			/// </summary>
 			public static bool[] SpawnsWithCustomName = Factory.CreateBoolSet(453);
+
+			// IDs taken NPC.AI_007_TryForcingSitting
```
Comment (JavidPack) [inline patches/tModLoader/Terraria/ID/NPCID.TML.cs]: ->IDs taken from...

File: ExampleMod/Content/Tiles/ExampleHerb.cs (hunk 1 above)
Comment (direwolf420) [reply ExampleMod/Content/Tiles/ExampleHerb.cs:109]: StyleAlch is -1, offsetY is set to -2 here, because vanilla herbs seem to have an offset regarding the placement preview for some reason. I added a comment to clarify this
