### PR TITLE
Torch fixes (Smart cursor, Biome torch/campfire)

### LINKED ISSUE #1383: [1.3 and 1.4] Modded torches lack "smart cursor" support by default
### Description
Torches have a few special behaviors in vanilla, that tml mostly supports by default (no modder boilerplate required), except "smart cursor". Providing this support on tmls side by default will bring torches fully in line with vanilla behavior.

### What does this proposal attempt to solve or improve?
What is supported by tml:
* Dry torch, water torch and glowstick handling with "smart select" (selected item depends on the tile the player is mouseovering)
* Torch flames

What is not supported by tml:
* "Smart cursor" (the game auto-aims at a suitable tile position to do things in - in the torches case, place it at an appropriate location around the player with the least amount of light)

### Which (other) solutions should be considered?
The modder writing their own custom smart cursor code (status quo), no consistency with other mods or vanilla guaranteed.

### Bonus
1.3:
* The method responsible for this is `Player.SmartCursor_Torch`, which currently only works with the vanilla torch tile type (4).

1.4:
* There exists `ItemID.Sets.WaterTorches`, which is not compatible with modded torches as its always checked against the vanilla torch tile type (4) first.
* The method responsible for this is `SmartCursorHelper.Step_Torch` and works the same as the 1.3 equivalent.

### LINKED ISSUE #2475: [1.4] [Feature Proposal] Torch God Manipulation Hook
### Do you intend to personally contribute/program this feature?

Yes

### I would like to see this change made to improve my experience with

Mod capability as a Modder

### Description

Add a new hook that allows modders to control whether a Torch God replacement torch should be placed and what tile ID and style should be used.

### What does this proposal attempt to solve or improve?

Allows modders to provide custom biome torches, among other things.

### Which (other) solutions should be considered?

Requires discussion.

### PR DESCRIPTION
**Pull request by JavidPack**
Fixes a variety of torch related issues:

Fixes #1383 - Support torch smart cursor behavior
Closes #1439 - Support torch smart cursor, use correct hold item dust and light when smart
Closes #2031 - Replace AutoLightSelect hook, fix ItemID.Sets.WaterTorches and ItemID.Sets.Torches usage
Fixes #2475 - Support for biome torch selection
Closes #2476 - Support for biome torch selection

# Existing Behavior
Since 1.4, the `ModItem.AutoLightSelect` hook has not been hooked up, meaning that all modded torches would be assumed to be dry torches for the purposes of auto select.

Modded torches would also attempt to place underwater even if they shouldn't, immediately breaking. 

Modded glowsticks and torches would not automatically end up in the correct duplication mode category.

Modded torches would not be considered for smart cursor placement. (Torches smart place about 10 tiles away from each other, currently modded torches will be ignored when placing vanilla torches)

Modded Campfires would not work with the block replace feature. Modded campfires would not work with Marshmallow on a stick cooking feature.

Modded Biome Torch and Biome Campfire manipulation are not possible. In vanilla, the biome torch feature allows normal torches to be automatically placed as a different torch depending on current biome.

No Campfire example.

No water torch example.

ExampleLamp and ExampleMusicBoxTile have incomplete TileObjectData, resulting in missing drops.

No `TileObjectData.newSubTile` examples in ExampleMod.

# PR Implementation

All of the above are fixed.

`ModItem.AutoLightSelect` is removed, vanilla sets `ItemID.Sets.Torches`, `ItemID.Sets.WaterTorches`, and TML added `ItemID.Sets.Glowsticks` replace it in functionality.

Biome torch/campfire support added via `ModBiome`.

TorchID approach used in vanilla for hold effects such as dust and light is not used. I think it would needlessly complicate code and modders wouldn't be happy to have to change their torches so much. There is a concern about HoldItem being called on the ContentSamples Item instance.

# ExampleMod changes

ExampleSurfaceBiome will cause ExampleTorch and ExampleCampfire to be used as biome torch/campfire.

ExampleCampfire tile/item added. Showcases rightclick and hitwire shared code. 

ExampleWaterTorch added.

ExampleTorch ModTile augmented with ExampleWaterTorch-specific `newSubTile` to support water placement.

# Short Summary
- Biome Torch/Campfire (Torch Gods Favor) support has been added. `ModBiome` can now dictate the appropriate item to auto swap.
- Various torch issues have been fixed: Smart cursor, underwater placement, duplication menu category
- Block Swap feature now supports modded Campfire tiles.
- `ExampleWaterTorch` added. `ExampleCampfire` added.

# Porting Notes
- (tModPorter) Remove `ModItem.AutoLightSelect` hooks. Add `ItemID.Sets.Torches[Type]`, `ItemID.Sets.WaterTorches[Type]`, or `ItemID.Sets.Glowsticks[Type]` to `SetStaticDefaults` when appropriate.
- (Optional) Remove `ModItem.ModifyResearchSorting` code for Torches and Glowsticks if corresponding `ItemID.Sets` is set, it is no longer needed.
- (Optional) Add biome torch and biome campfire support to `ModBiome` classes by overriding `BiomeTorchItemType` or `BiomeCampfireItemType`
- (Optional) Confirm that `HoldItem` code in torch items doesn't affect the item instance or have other side effects.
- (Optional) Compare Torch `ModTile` code in your mod against `ExampleTorch` if you previously used it as a guide. `MouseOver` was missing previously and the `SetDrawPositions` code was incorrect. `TileObjectData.newTile.CopyFrom(TileObjectData.GetTileData(TileID.Torches, 0));` usage might simplify your code as well.

### CODE REVIEW

File: patches/tModLoader/Terraria/Player.cs.patch [hunk 1]
```diff
@@ -6191,6 +6334,15 @@
  		if (isPettingAnimal) {
  			int num = miscCounter % 14 / 7;
  			CompositeArmStretchAmount stretch = CompositeArmStretchAmount.ThreeQuarters;
+@@ -38865,7 +_,7 @@
+ 					if (Main.tile[num5, num6] == null)
+ 						Main.tile[num5, num6] = new Tile();
+ 
+-					if (Main.tile[num5, num6].active() && Main.tile[num5, num6].type == 215 && Main.tile[num5, num6].frameY < 54) {
++					if (Main.tile[num5, num6].active() && TileID.Sets.Campfire[Main.tile[num5, num6].type] && Main.tile[num5, num6].frameY < 54) {
```
Comment (Chicken-Bones) [inline patches/tModLoader/Terraria/Player.cs.patch:6338]: do we put the same frame requirements on modded campfires? No reason not to I suppose, but might be worth commenting somewhere.

File: patches/tModLoader/Terraria/Player.cs.patch [hunk 2]
```diff
@@ -6178,6 +6301,26 @@
  		for (int i = 0; i < 1000; i++) {
  			Projectile projectile = Main.projectile[i];
  			if (projectile.active && projectile.owner == Main.myPlayer && ProjectileID.Sets.TurretFeature[projectile.type])
+@@ -38475,6 +_,11 @@
+ 			float B = 0.8f;
+ 			int num = 0;
+ 			int num2 = BiomeTorchHoldStyle(sItem.type);
++			if (num2 >= ItemID.Count) {
++				// This could be a different hook, but then modders would have to move code. TorchID could be used, but it would be a lot of work managing another modded ID and would limit torch lighting and dust behavior to the vanilla pattern.
++				ContentSamples.ItemsByType[num2]?.ModItem?.HoldItem(this);
```
Comment (Chicken-Bones) [inline patches/tModLoader/Terraria/Player.cs.patch]: Please use `ItemLoader.GetItem(num2)`, it's what we use for other type-based hooks (like `AnglerQuestChat` or `ExtractinatorUse`. It's safer than accidentally modifying the content samples item.

Need to add a comment to `ExampleTorch` when overriding the hook. Note that due to biome select torch god's favour, the player may not actually have an `ExampleTorch` in their inventory when this hook is called, so no modifications should be made to the item instance.

File: patches/tModLoader/Terraria/Player.cs.patch [hunk 3]
```diff
@@ -5534,6 +5648,15 @@
  			if ((!overrideCanPlace.HasValue || overrideCanPlace.Value) && TileObjectData.CustomPlace(tileToCreate, previewPlaceStyle))
  				TileObject.CanPlace(tileTargetX, tileTargetY, tileToCreate, previewPlaceStyle, direction, out var _, onlyCheck: true, forcedRandom);
  		}
+@@ -33782,7 +_,7 @@
+ 		overrideCanPlace = null;
+ 		forcedRandom = null;
+ 		if (UsingBiomeTorches && tileToCreate == 215 && previewPlaceStyle == 0)
```
Comment (Chicken-Bones) [inline patches/tModLoader/Terraria/Player.cs.patch:5650]: is this meant to have a `TileID.Sets.Campfires` check instead of `215`?

File: patches/tModLoader/Terraria/Player.cs.patch [hunk 4]
```diff
@@ -5064,6 +5116,68 @@
...
+ 			style = 4383;
+ 
++		if (CurrentSceneEffect.biomeTorchItemType.value > -1) {
++			style = CurrentSceneEffect.biomeTorchItemType.value;
++		}
++
+ 		return style;
+ 	}
+ 
+-	public int BiomeCampfirePlaceStyle(int style)
```
Comment (Chicken-Bones) [inline patches/tModLoader/Terraria/Player.cs.patch]: Comment out original overload where changes are non-obvious please

File: patches/tModLoader/Terraria/Player.cs.patch [hunk 5]
```diff
@@ -5064,6 +5116,68 @@
  		}
  
  		return data;
+@@ -30981,7 +_,7 @@
+ 		}
+ 	}
+ 
+-	public int BiomeTorchPlaceStyle(int style)
```
Comment (Chicken-Bones) [inline patches/tModLoader/Terraria/Player.cs.patch]: As below

File: patches/tModLoader/Terraria/Player.cs.patch [hunk 6]
```diff
@@ -5047,10 +5080,29 @@
...
  
  		if (tile.type == 215 && tile.type == createTile)
  			return tile.frameX / 54 != num;
++		*/
++
++		if (TileID.Sets.Campfire[tile.type] && TileID.Sets.Campfire[createTile]) {
++			if (tile.frameX / 54 == num)
++				return tile.type != createTile;
++
++			return true;
```
Comment (Chicken-Bones) [inline patches/tModLoader/Terraria/Player.cs.patch]: `return tile.type != createTile || tile.frameX / 54 != num`

Comment (Chicken-Bones) [reply patches/tModLoader/Terraria/Player.cs.patch]: Might be nice to edit the torch patch above with the same `||` formatting, and split the commented vanilla code into 2 groups  (torch and campfire), each preceeding the modded variant.

File: patches/tModLoader/Terraria/ID/ContentSamples.cs.patch [hunk 7]
```diff
@@ -35,6 +35,27 @@
...
++			*/
++			if (ItemID.Sets.Glowsticks[item.type]) {
+ 				if (item.type == 282)
+ 					orderInGroup = -1;
+ 
+@@ -332,6 +_,9 @@
+ 						return ItemGroup.Torches;
+ 					}
+ 
++					if(TileID.Sets.Torch[item.createTile])
```
Comment (Chicken-Bones) [inline patches/tModLoader/Terraria/ID/ContentSamples.cs.patch]: ` ` spacing before bracket

File: patches/tModLoader/Terraria/ModLoader/ModSceneEffect.cs [hunk 8]
```diff
@@ -33,6 +33,16 @@ public abstract partial class ModSceneEffect : ModType
...
+	/// <summary>
+	/// The torch item type that will be placed when under the effect of biome torches
+	/// </summary>
+	public virtual int BiomeTorchItemType => -1;
+
+	/// <summary>
+	/// The campfire item type that will be placed when under the effect of biome torches
+	/// </summary>
+	public virtual int BiomeCampfireItemType => -1;
+
```
Comment (Chicken-Bones) [inline patches/tModLoader/Terraria/ModLoader/ModSceneEffect.cs]: Should go in `ModBiome`. `ModSceneEffect` provides purely visual and audio changes. I don't like the idea of it affecting gameplay.

**Review by Chicken-Bones — CHANGES_REQUESTED** [review]

File: patches/tModLoader/Terraria/Player.cs.patch (hunk 1 above)
Comment (JavidPack) [reply patches/tModLoader/Terraria/Player.cs.patch:6338]: They do, I'll make a note in the Set docs.

File: patches/tModLoader/Terraria/Player.cs.patch (hunk 3 above)
Comment (JavidPack) [reply patches/tModLoader/Terraria/Player.cs.patch:5650]: It is not, this is specifically checking for the original campfire item, since that is the only one that will be changed by the biome campfire feature.

File: patches/tModLoader/Terraria/Player.cs.patch (hunk 2 above)
Comment (JavidPack) [reply patches/tModLoader/Terraria/Player.cs.patch]: Got it.
