### PR TITLE
Fix #4176

### LINKED ISSUE #4176: LoaderUtils.MustOverrideTogether doesn't display method name
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

The method names are not contained in the error message anymore. To test, comment out `ExampleStatIncreasePlayer.CopyClientState`.

image

Also, `ModPlayer.SaveData` and `LoadData` are no longer detected as missing, something broke there as well. I think it just needs to match the others in form

image

Likely a regression of https://github.com/tModLoader/tModLoader/pull/4089, which is already in stable.

### Log File

_No response_

### Steps to reproduce

_No response_

### Expected Behavior

_No response_

### Actual Behavior

_No response_

### Reproduction frequency

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by JavidPack**
Not sure if the approach is inefficient, I don't know the internal details of the rewrite all too well, but it does seem to fix the issue.

### CODE REVIEW

File: patches/tModLoader/Terraria/ModLoader/Core/LoaderUtils.cs [hunk 1]
```diff
@@ -246,7 +246,7 @@ public static void MustOverrideTogether<T>(T t, params Expression<Func<T, Delega
 	{
 		int c = methods.Count(m => HasOverride(t, m));
 		if (c > 0 && c < methods.Length)
-			throw new Exception($"{t!.GetType()} must override all of ({string.Join('/', methods.Select(m => m.Name))}) or none");
+			throw new Exception($"{t!.GetType()} must override all of ({string.Join('/', methods.Select(m => m.ToOverrideQuery().Method.Name))}) or none");
```
Comment (Chicken-Bones) [inline patches/tModLoader/Terraria/ModLoader/Core/LoaderUtils.cs]: This is perfectly fine, but it's simpler to use `.ToMethodInfo()`.

See the implementation of `.ToOverrideQuery()` for details.
