### PR TITLE
Qualify the dotnet path of created mod to solve error on editors such as Rider

### LINKED ISSUE #3942: Rider Error: Invalid exe path: ...\dotnet
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

By default, Rider was not able to start / debug the game from mod project.

My tModLoader installation is here "E:\SteamLibrary\steamapps\common\tModLoader". 
When trying to launch the game from within the IDE I received this error:
`Error: Invalid exe path: E:\SteamLibrary\steamapps\common\tModLoader\dotnet` within "Run/Debug Configurations" window.

The issue was mentioned on Discord server at least 2 times and there are answers on how to solve that.
The issue is within `Properties/launchSettings.json:5`. 
Windows can't find dotnet as it needs dotnet.exe.

The best Discord solution [part1](https://discord.com/channels/103110554649894912/534215632795729922/1092119127394635776) and [part2](https://discord.com/channels/103110554649894912/534215632795729922/1092120129388691598) is to add
```
<PropertyGroup>
    <DotNetPath Condition=" '$(OS)' == 'Windows_NT' ">dotnet.exe</DotNetPath>
    <DotNetPath Condition=" '$(OS)' == 'Unix' ">dotnet</DotNetPath>
    <DotNetPath Condition=" '$(DotNetPath)' == '' ">dotnet</DotNetPath>
</PropertyGroup>
```
inside of .csproj
and replace `dotnet` with `$(DotnetPath)` inside of launchSettings.json.

This seems to be the best way to solve the issue out of the box on Windows, without breaking it on other platforms.

### Log File

_No response_

### Steps to reproduce

1. Create mod with TML
2. Open project with Rider
3. Start run configuration

### Expected Behavior

Configuration runs smoothly

### Actual Behavior

Error: Invalid exe path: ...\dotnet

### Reproduction frequency

_No response_

### Additional Information

Solved in Discord, solution present

### PR DESCRIPTION
**Pull request by Cyrillya**
**Code written by: [steviegt6](https://github.com/steviegt6) (tomat)**

Fixes #3942
Editors such as Rider don't handle extensions. A more fully-qualified name has to be given instead

### How did I fix it?
Added this to `.csproj` file of created mod
```
<DotNetPath Condition=" '$(OS)' == 'Windows_NT' ">dotnet.exe</DotNetPath>
<DotNetPath Condition=" '$(OS)' == 'Unix' ">dotnet</DotNetPath>
<DotNetPath Condition=" '$(DotNetPath)' == '' ">dotnet</DotNetPath>
```

And replaced `dotnet` with `$(DotnetPath)` inside of launchSettings.json.

### CODE REVIEW

**Comment by Chicken-Bones** [comment]
Call it `$(DotNetName)` and put it in `tMLMod.targets`, then it's approved

**Comment by Chicken-Bones** [comment]
Apparently the same doesn't apply to the `"dotnet ...` part of `<Target Name="BuildMod" AfterTargets="Build">`? Or should that be changed too?

**Comment by steviegt6** [comment]
I'm surprised to see my code spread as far and wide as it has. I'm not thrilled with this solution due to how it interacts with runner generation in IDEs like Rider; these environment variables *work* but they get inlined when creating runners, meaning that if they ever change they aren't guaranteed to be updated.

I've recently taken to a simpler approach:
```xml
{
  "profiles": {
    "Terraria Client (dotnet)": {
      "commandName": "Executable",
      "executablePath": "dotnet",
      "commandLineArgs": "$(tMLPath)",
      "workingDirectory": "$(tMLSteamPath)"
    },
    "Terraria Server (dotnet)": {
      "commandName": "Executable",
      "executablePath": "dotnet",
      "commandLineArgs": "$(tMLServerPath)",
      "workingDirectory": "$(tMLSteamPath)"
    },
    "Terraria Client (dotnet.exe)": {
      "commandName": "Executable",
      "executablePath": "dotnet.exe",
      "commandLineArgs": "$(tMLPath)",
      "workingDirectory": "$(tMLSteamPath)"
    },
    "Terraria Server (dotnet.exe)": {
      "commandName": "Executable",
      "executablePath": "dotnet.exe",
      "commandLineArgs": "$(tMLServerPath)",
      "workingDirectory": "$(tMLSteamPath)"
    }
  }
}
```

Also, I can't say I'm particularly thrilled to see this used so much without asking me despite being committed exclusively to an implicitly-ARR repository. Absolutely zero credit isn't appreciated no matter how simple it is.

**Comment by steviegt6** [comment]
> Apparently the same doesn't apply to the `"dotnet ...` part of `<Target Name="BuildMod" AfterTargets="Build">`? Or should that be changed too?

This is (sort of) managed by whatever version of MSBuild/dotnet the IDE or `dotnet` CLI tool is running. Rider resolves this fine (it just runs the command, so as long as it's on the PATH it will resolve correctly).

I think if Rider just ignored the missing file resolution error for the launch profiles it would end up running fine anyway.

File: patches/tModLoader/Terraria/ModLoader/UI/UICreateMod.cs [hunk 1]
```diff
@@ -262,6 +262,9 @@ internal string GetModCsproj(string modNameTrimmed)
     <TargetFramework>net6.0</TargetFramework>
     <PlatformTarget>AnyCPU</PlatformTarget>
     <LangVersion>latest</LangVersion>
+    <DotNetPath Condition="" '$(OS)' == 'Windows_NT' "">dotnet.exe</DotNetPath>
+    <DotNetPath Condition="" '$(OS)' == 'Unix' "">dotnet</DotNetPath>
+    <DotNetPath Condition="" '$(DotNetPath)' == '' "">dotnet</DotNetPath>
```
Comment (steviegt6) [inline patches/tModLoader/Terraria/ModLoader/UI/UICreateMod.cs]: It may make more sense to define these in one of the preexisting targets files rather than in the mod project itself.

File: patches/tModLoader/Terraria/ModLoader/UI/UICreateMod.cs [hunk 2]
```diff
@@ -286,13 +289,13 @@ internal string GetLaunchSettings()
   ""profiles"": {{
     ""Terraria"": {{
       ""commandName"": ""Executable"",
-      ""executablePath"": ""dotnet"",
+      ""executablePath"": ""$(DotNetPath)"",
```
Comment (steviegt6) [inline patches/tModLoader/Terraria/ModLoader/UI/UICreateMod.cs]: Does there exist infrastructure for updating this file?

Comment (Chicken-Bones) [reply patches/tModLoader/Terraria/ModLoader/UI/UICreateMod.cs]: There does not. However the number of Rider users is extremely small. VS has no problem launching `dotnet` on Windows.

**Comment by Chicken-Bones** [comment]
> these environment variables work but they get inlined when creating runners, meaning that if they ever change they aren't guaranteed to be updated.

That's ok, since apparently this is a platform deficiency. The only thing to solve here is the first time people open a project in Rider on Windows

**Comment by Cyrillya** [comment]
> Also, I can't say I'm particularly thrilled to see this used so much without asking me despite being committed exclusively to an implicitly-ARR repository. Absolutely zero credit isn't appreciated no matter how simple it is.

Sorry I didn't mentioned you for creating this. But I just saw this in the issue I referenced (#3942) and I really didn't know who the author is

**Comment by Cyrillya** [comment]
> Call it `$(DotNetName)` and put it in `tMLMod.targets`, then it's approved

Done. Hope I didn't do anything wrong
