### PR TITLE
Fix #3980 (Show class name in GetLoadableTypesException)

### LINKED ISSUE #3980: Cross-mod GetLoadableTypesException could be improved to show Type causing issue
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Reported here: https://discord.com/channels/103110554649894912/445276626352209920/1184110644463669268

When inheriting from a class in another mod, and that mod isn't loaded, the exception message is unhelpful in identifying the issue because tModLoader doesn't capture report the Type in the exception message

We can "put `asm.GetType(mType.FullName, throwOnError: true, ignoreCase: false)` in a helper method which has a try-catch and puts `mType.FullName` into the exception message" to fix this. 

The fixed solution should allow modders to identify the source Type/file of the issue.

### Log File

```
[17:38:40.967] [.NET ThreadPool Worker/INFO] [tML]: Sandboxing: TheConfectionRebirth (Confection REBAKED (Hallow Alternative)) v0.20.0.1
[17:38:41.249] [.NET ThreadPool Worker/DEBUG] [tML]: Assembly Resolve: TheConfectionRebirth, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> ThoriumMod, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[17:38:41.437] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.IO.FileNotFoundException: Could not load file or assembly 'ThoriumMod, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Terraria.ModLoader.Core.AssemblyManager.GetLoadableTypes(ModLoadContext mod, MetadataLoadContext mlc) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 325
   at Terraria.ModLoader.Core.AssemblyManager.ModLoadContext.LoadAssemblies() in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 70
   at Terraria.ModLoader.Core.AssemblyManager.InstantiateMods(List`1 modsToLoad, CancellationToken token) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 262
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 120
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

[17:38:41.442] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
Terraria.ModLoader.Exceptions.GetLoadableTypesException: This mod seems to inherit from classes in another mod. Use the [ExtendsFromMod] attribute to allow this mod to load when that mod is not enabled.
Could not load file or assembly 'ThoriumMod, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at Terraria.ModLoader.Core.AssemblyManager.GetLoadableTypes(ModLoadContext mod, MetadataLoadContext mlc) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 325
   at Terraria.ModLoader.Core.AssemblyManager.ModLoadContext.LoadAssemblies() in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 70
   at Terraria.ModLoader.Core.AssemblyManager.InstantiateMods(List`1 modsToLoad, CancellationToken token) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 262
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 120
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

[17:38:41.447] [.NET ThreadPool Worker/INFO] [tML]: Launched Outside of Steam. Skipping attempt to trigger 'verify local files' in Steam. If error persists, please attempt this manually
[17:38:41.448] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading TheConfectionRebirth v0.20.0.1
The mod(s) have been automatically disabled.
Terraria.ModLoader.Exceptions.GetLoadableTypesException: This mod seems to inherit from classes in another mod. Use the [ExtendsFromMod] attribute to allow this mod to load when that mod is not enabled.
Could not load file or assembly 'ThoriumMod, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'ThoriumMod, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'ThoriumMod, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Terraria.ModLoader.Core.AssemblyManager.GetLoadableTypes(ModLoadContext mod, MetadataLoadContext mlc) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 325
   --- End of inner exception stack trace ---
   at Terraria.ModLoader.Core.AssemblyManager.GetLoadableTypes(ModLoadContext mod, MetadataLoadContext mlc) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 332
   at Terraria.ModLoader.Core.AssemblyManager.ModLoadContext.LoadAssemblies() in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 70
   at Terraria.ModLoader.Core.AssemblyManager.InstantiateMods(List`1 modsToLoad, CancellationToken token) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 262
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 120
[17:38:41.456] [.NET ThreadPool Worker/INFO] [tML]: Disabling Mod: TheConfectionRebirth
```

### Steps to reproduce

_No response_

### Expected Behavior

_No response_

### Actual Behavior

_No response_

### Reproduction frequency

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by JavidPack**
~~Replicated the error by inheriting from a class in a mod that was not loaded. The stacktrace doesn't match the reported error, however, so I still need to verify if the `asm.GetType(mType.FullName, throwOnError: true, ignoreCase: false)` should be try-catched as well.~~

A previous commit, #4033, fixed some related errors, but inheritance issues still persist.

The diff is a little hard to follow:

IsLoadable was augmented to throw an error with the classname to help modders locate the issue.

The following code was added to handle nested classes of inheriting classes. (`<>c` stuff)
```cs
if (type.DeclaringType != null && !IsLoadable(mod, type.DeclaringType))
	return false;
```
	
The following code was used to test. Variations of this code with lambdas was tested to ensure the fixes worked in tandem for their respective use-cases.
```cs
public class InheritsFromCSB : CheatSheet.CheatSheetButton
{
	public InheritsFromCSB(Asset<Texture2D> texture) : base(texture) {
			
	}
}

public class InheritsFromInheritsFromCSB : InheritsFromCSB
{
	public InheritsFromInheritsFromCSB(Asset<Texture2D> texture) : base(texture) {
		On_Player.PickTile += (On_Player.orig_PickTile orig, Player self, int x, int y, int pickPower) => {
			orig(self, x, y, pickPower);
		};
	}
}
```
A modder fixing this code only needs to annotate `InheritsFromCSB` with `[ExtendsFromMod("CheatSheet")]`. The class that inherits from `InheritsFromCSB` will not need to be annotated.

Expected Error Message:
image

### CODE REVIEW

File: patches/tModLoader/Terraria/ModLoader/Core/AssemblyManager.cs [hunk 1]
```diff
@@ -339,18 +339,29 @@ internal static bool FirstModInStackTrace(StackTrace stack, out string modName)
...
+				return false;
 
-		return type.GetInterfaces().All(i => IsLoadable(mod, i));
+			return type.GetInterfaces().All(i => IsLoadable(mod, i));
+		}
+		catch (FileNotFoundException e) {
+			throw new Exceptions.GetLoadableTypesException(
+				$"This mod seems to inherit from classes in another mod. Use the [ExtendsFromMod] attribute to allow this mod to load when that mod is not enabled.\n\nThe \"{type.FullName}\" class caused this error." + "\n\n" + e.Message,
+				e
+			);
```
Comment (Chicken-Bones) [inline patches/tModLoader/Terraria/ModLoader/Core/AssemblyManager.cs]: Less complicated code/error message duplication if you do. Then you can just conditionally add the `The \"{type.FullName}\" class caused this error.` line if `Data["type"] is Type t`
```cs
catch (Exception e) {
	e.Data["type"] = type;
	throw;
}
```
