### PR TITLE
Fix Modded Droplet Gores (resolves #2049)

### LINKED ISSUE #2049: [1.4] Water droplet gore from modded biomes appear as granite golem head gores
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Self-explanatory, custom water droplet gores ive made and set for the WaterStyle's GetDropletGore creates a vanilla gore instead of the modded one

[DropletStuff.zip](https://github.com/tModLoader/tModLoader/files/7776069/DropletStuff.zip)

### Log File

_No response_

### Steps to reproduce

_No response_

### Expected Behavior

_No response_

### Actual Behavior

_No response_

### Reproduction frequency

Seems to be always, other people have encountered it too

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by steviegt6**
### What is the bug?
#2049

### How did you fix the bug?
Added a simple conditional for checking if the water style is that of a modded type, and instead use `GetDropletGore` instead of vanilla's hardcoded calculations.

### Are there alternatives to your fix?
No.

Resolves #2049.

### CODE REVIEW

File: patches/tModLoader/Terraria/GameContent/Drawing/TileDrawing.cs.patch [hunk 1]
```diff
@@ -99,6 +99,15 @@
...
  			_specialTilesCount++;
+@@ -5094,6 +_,8 @@
+ 
+ 			Vector2 position = new Vector2(i * 16, j * 16);
+ 			int type = 706;
++			if (Main.waterStyle >= Main.maxLiquidTypes)
++				type = LoaderManager.Get<WaterStylesLoader>().Get(Main.waterStyle).GetDropletGore();
+ 			if (Main.waterStyle == 12)
+ 				type = 1147;
+ 			else if (Main.waterStyle > 1)
```
Comment (Mirsario) [inline patches/tModLoader/Terraria/GameContent/Drawing/TileDrawing.cs.patch]: Code below overrides this.

**Review by Mirsario — CHANGES_REQUESTED** [review]

File: patches/tModLoader/Terraria/GameContent/Drawing/TileDrawing.cs.patch (hunk 1 above)
Comment (steviegt6) [reply patches/tModLoader/Terraria/GameContent/Drawing/TileDrawing.cs.patch]: When the CTRL+S doesn't work!

**Review by Mirsario — APPROVED** [review]
