### PR TITLE
Various checks for latest Terraria install, Fix #1979

### LINKED ISSUE #1979: 1.4 Alpha check Terraria version
### Version

Latest public-1.4-alpha

### OS

Linux

### Platform

Steam

### Description

Currently the 1.4 alpha (and maybe the stable version) does not check for the Terraria version, and instead claims that game assets are missing. Attached is my crashlog for today, containing the crashes for Glow 310 missing, and after a few tries I made a fake Glow 310 file and it complained that Extra 244 was missing, I kept creating files and it kept discovering new missing ones until I updated to the latest vanilla terraria on steam which contained the missing game assets.
[client-crashlog.txt](https://github.com/tModLoader/tModLoader/files/7574337/client-crashlog.txt)

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7574344/client.log)
Here is the client log after I created around 15 fake buff files and then realized I was probably on the wrong version of the game.

### Steps to reproduce

Have old version of terraria. 
Install tmodloader.
Get in-descriptive error message.

### Expected Behavior

It should warn the user about the wrong version.

### Actual Behavior

It only notices missing asset files.

### Reproduction frequency

Any time when versions don't match.

### Additional Information

My temporary solution for users on reddit: [https://old.reddit.com/r/Terraria/comments/qxnlqw/tmodloader_14_issues/hlddgxo/](url)

### PR DESCRIPTION
**Pull request by JavidPack**
Still to do: 
Maybe we need some sort of checklist or task list token to remind us of all the places things need to update when a new version comes out.

### CODE REVIEW

File: patches/tModLoader/Terraria/ModLoader/Engine/TerrariaSteamClient.cs [hunk 1]
```diff
@@ -140,6 +140,11 @@ public enum LaunchResult
 					return;
 				}
 
+				int TerrariaBuildID = SteamApps.GetAppBuildId();
+				Logger.Info("Terraria BuildID: " + TerrariaBuildID);
+				if (TerrariaBuildID < 9653812) // Currently v1.4.4.4. Update this when any Terraria update changes any asset.
```
Comment (Chicken-Bones) [inline patches/tModLoader/Terraria/ModLoader/Engine/TerrariaSteamClient.cs]: Make this a constant at the top of the file.

Comment (Chicken-Bones) [reply patches/tModLoader/Terraria/ModLoader/Engine/TerrariaSteamClient.cs]: Are these UUIDs or do they actually increment?

File: patches/tModLoader/Terraria/Initializers/AssetInitializer.cs.patch [hunk 2]
```diff
@@ -37,12 +37,33 @@
...
 +
 +			UICommon.LoadTextures(); // Added by TML.
++		}
++
++		private static bool canaryFilesChecked;
++		internal static void CheckCanaryFiles() {
++			if (canaryFilesChecked)
++				return;
++
++			// These checks ensure the latest Terraria is installed.
```
Comment (Chicken-Bones) [inline patches/tModLoader/Terraria/Initializers/AssetInitializer.cs.patch]: Is this necessary? I'd prefer a `File.Exists` in `InitTMLContentManager`, since we have the `vanillaContentFolder` there at the time, and it is mandatory

**Review by Chicken-Bones — CHANGES_REQUESTED** [review]

File: patches/tModLoader/Terraria/ModLoader/Engine/TerrariaSteamClient.cs (hunk 1 above)
Comment (JavidPack) [reply patches/tModLoader/Terraria/ModLoader/Engine/TerrariaSteamClient.cs]: They increment only.

File: patches/tModLoader/Terraria/Initializers/AssetInitializer.cs.patch (hunk 2 above)
Comment (JavidPack) [reply patches/tModLoader/Terraria/Initializers/AssetInitializer.cs.patch]: done

File: patches/tModLoader/Terraria/ModLoader/Engine/TerrariaSteamClient.cs [hunk 3]
```diff
@@ -140,6 +141,11 @@ public enum LaunchResult
 					return;
 				}
 
+				int TerrariaBuildID = SteamApps.GetAppBuildId();
+				Logger.Info("Terraria BuildID: " + TerrariaBuildID);
+				if (TerrariaBuildID < LatestTerrariaBuildID)
```
Comment (Chicken-Bones) [inline patches/tModLoader/Terraria/ModLoader/Engine/TerrariaSteamClient.cs]: can you pipe this back to the main process via an error code? This should be the primary point of failure.

File: patches/tModLoader/Terraria/Main.TML.cs [hunk 4]
```diff
@@ -190,6 +190,11 @@ public partial class Main
 				ErrorReporting.FatalExit(Language.GetTextValue("tModLoader.ContentFolderNotFound"));
 			}
 
+			// Canary file, ensures that Terraria has updated to at least the version this tModLoader was built for
+			if (!File.Exists(Path.Combine(vanillaContentFolder, "Images", "Projectile_981.xnb"))) {
+				ErrorReporting.FatalExit(Language.GetTextValue("tModLoader.TerrariaOutOfDateMessage"));
```
Comment (Chicken-Bones) [inline patches/tModLoader/Terraria/Main.TML.cs:195]: Is this needed given the build check ID below? Is there a possibility of someone having an incomplete Terraria install? If so, maybe this should just tell people to verify their terraria local files instead.

**Review by Chicken-Bones — CHANGES_REQUESTED** [review]

**Review by Chicken-Bones — APPROVED** [review]
