### PR TITLE
Fix dotnet detection under steam runtime. Fixes #4450

### LINKED ISSUE #4450: Dotnet SDK is not being found correctly on Linux
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

The dotnet SDK is not properly being found. Not sure what exactly the issue is, but [this process](https://github.com/tModLoader/tModLoader/blob/stable/patches/tModLoader/Terraria/ModLoader/UI/UIModSources.cs#L350-L355) doesn't seem to be outputting correctly. Log file is attached, as you can see nothing is printed after `dotnet --list-sdks` is ran and I think the same is the case for `which dotnet` ran earlier - `which dotnet` runs correctly in a terminal, along with `dotnet --list-sdks`. I've also seen multiple people report this on multiple distros.

I've been able to workaround by launching tmodloader from the start-tModLoader.sh script

### Log File

[client.log pastebin](https://paste.ppeb.me/yaperokuku.txt)
[client.log](https://github.com/user-attachments/files/17790639/client.log)

[environment.log pastebin](https://paste.ppeb.me/locosoyawa.txt)
[environment.log](https://github.com/user-attachments/files/17790770/environment.log)

### Steps to reproduce

_No response_

### Expected Behavior

_No response_

### Actual Behavior

_No response_

### Reproduction frequency

Every time

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by covers1624**
### What is the bug?
https://github.com/tModLoader/tModLoader/issues/4450 tModLoader fails to detect dotnet when running under steam runtime/pressure vessel on Linux.

### How did you fix the bug?
We find and execute dotnet via `steam-runtime-launch-client` as per the steam [runtime documentation](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/slr-for-game-developers.md#running-commands-outside-the-container).

Cleaned up the path detection in `tModPorter.sh` as per @Chicken-Bones's recommendation.

Added error reporting to `tModPorter.sh` if dotnet is missing or not found.

### Are there alternatives to your fix?
No.

### CODE REVIEW

File: patches/tModLoader/Terraria/ModLoader/UI/UIModSources.cs [hunk 1]
```diff
@@ -296,12 +296,14 @@ private static string GetCommandToFindPathOfExecutable()
...
 	{
 		if (GetCommandToFindPathOfExecutable() is string cmd) {
-			yield return Process.Start(new ProcessStartInfo {
+			string whereResult = ModCompile.StartOnHost(new ProcessStartInfo {
 				FileName = cmd,
 				Arguments = "dotnet",
 				UseShellExecute = false,
 				RedirectStandardOutput = true
 			}).StandardOutput.ReadToEnd().Split("\n")[0].Trim();
+			if (!string.IsNullOrWhiteSpace(whereResult))
```
Comment (Chicken-Bones) [inline patches/tModLoader/Terraria/ModLoader/UI/UIModSources.cs]: I feel this would be better placed in `DoesDotnetWork`

**Comment by JavidPack** [comment]
Thanks a bunch. We've done some additional testing here and it looks like it's a good solution.
