### PR TITLE
Fix language packs don't work issue

### LINKED ISSUE #2615: Language pack don't work
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Language pack don't work at all

### Log File

_No response_

### Steps to reproduce

1. Enable a resource pack for modifying text
2. Get into the game and check it. The text has not changed.

### Expected Behavior

The text should be changed

### Actual Behavior

The text doen't change

### Reproduction frequency

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Cyrillya**
### What is the bug?
Fixes #2615

### How did you fix the bug?
In `LanguageManager.UseSources`, I found that the `assetNameStart` used `ToLower()`
```
string name = ActiveCulture.Name;
string assetNameStart = ("Localization" + Path.DirectorySeparatorChar + name).ToLower();
LoadLanguage(ActiveCulture, processCopyCommands: false);
foreach (IContentSource item in sourcesFromLowestToHighest) {
	foreach (string item2 in item.GetAllAssetsStartingWith(assetNameStart)) {
		string extension = item.GetExtension(item2);
```
But it doesn't use `ToLower()` in the method it calls `IContentSource.GetAllAssetsStartingWith()`
```
IEnumerable<string> GetAllAssetsStartingWith(string assetNameStart, bool lower = false) =>
    EnumerateAssets().Where(s => s.StartsWith(assetNameStart));
```
So the `assetNameStart` never finds any asset name starts with `Localization\[LanguageName]`
The incoming parameter will only be `localization\[LanguageName]`, which is not uppercase

I replaced the method and call with these
```
string name = ActiveCulture.Name;
string assetNameStart = ("Localization" + Path.DirectorySeparatorChar + name).ToLower();
LoadLanguage(ActiveCulture, processCopyCommands: false);
foreach (IContentSource item in sourcesFromLowestToHighest) {
	// Added a "true" parameter so that it can search by lowercase paths
	foreach (string item2 in item.GetAllAssetsStartingWith(assetNameStart, true)) {
		string extension = item.GetExtension(item2);
```
```
IEnumerable<string> GetAllAssetsStartingWith(string assetNameStart, bool lower = false) {
	if (lower)
		return EnumerateAssets().Where(s => s.ToLower().StartsWith(assetNameStart));
	return EnumerateAssets().Where(s => s.StartsWith(assetNameStart));
}
```
Now it will find the correct file

However, it didn't end here, since I found that `item.GetExtension(item2)` can actually get nothing but an empty string
I looked into the vanilla code of `GetExtension()`, in `FileSystemContentSource.GetExtension()`
```
public string GetExtension(string assetName) {
	if (!_nameToAbsolutePath.TryGetValue(assetName, out string value))
		throw AssetLoadException.FromMissingAsset(assetName);

	return Path.GetExtension(value) ?? "";
}
```
I found it used `Path.GetExtension(value) ?? ""`, so I replaced  `item.GetExtension(item2)` with it:
```
string extension = Path.GetExtension(item2) ?? "";
```
And the language packs just started to work.
This could be a temporary solution.

### CODE REVIEW

**Comment by JavidPack** [comment]
There are fundamental issues with how the system has been changed by tmod. This probably solves a few of them. I went through similar issues when working on this same issue on https://github.com/tModLoader/tModLoader/compare/1.4...1.4_FixTextResoucePacks branch. I think we'll need feedback from the people who moved things around, see what the intention is for these methods and such, since they seem to have been changed for various purposes.

**Comment by Shiranui-Izayoi** [comment]
I know this pull request is a bit old. But where did you find the files? Are they on the steam download of TModLoader or do I need to do something else?

I have run into this as well and wanted to fix it. But I just can't find "patches" folder or "LanguageManager.UseSources".

**Comment by JavidPack** [comment]
> I know this pull request is a bit old. But where did you find the files? Are they on the steam download of TModLoader or do I need to do something else?
> 
> I have run into this as well and wanted to fix it. But I just can't find "patches" folder or "LanguageManager.UseSources".

No, the tmodloader download does not contain the tmodloader source code. To access the source code, you must follow the steps in https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-contributors. It is an involved process. If you aren't familiar with the source code already, fixing this will be very difficult. Please upvote the issue with 👍 if you'd like this issue prioritized.

**Comment by Mirsario** [comment]
Rebased after more than a year, and changed the solution a bit:
- `ToLower()` is replaced with `StringComparison` parameters for performance.
- Instead of using `Path.GetExtension` and thus breaking non-FS content sources, `FileSystemContentSource` now populates its extension lookup to allow paths with extensions in `GetExtension`, since that's what `EnumerateAssets` yields.

My apologies for this taking so long to be reviewed & merged.

[Hungarian replacing English](https://steamcommunity.com/sharedfiles/filedetails/?id=2441620742):
image

File: patches/tModLoader/Terraria/Localization/LanguageManager.cs.patch [hunk 1]
```diff
@@ -113,8 +113,13 @@
  		LoadLanguage(ActiveCulture, processCopyCommands: false);
 +		*/
  		foreach (IContentSource item in sourcesFromLowestToHighest) {
- 			foreach (string item2 in item.GetAllAssetsStartingWith(assetNameStart)) {
- 				string extension = item.GetExtension(item2);
+-			foreach (string item2 in item.GetAllAssetsStartingWith(assetNameStart)) {
+-				string extension = item.GetExtension(item2);
++			foreach (string item2 in item.GetAllAssetsStartingWith(assetNameStart, ignoreCase: true)) {
++				string extension = item.GetExtension(item2) ?? "";
```
Comment (Chicken-Bones) [inline patches/tModLoader/Terraria/Localization/LanguageManager.cs.patch:119]: no need for the null coalesce patch here

File: patches/tModLoader/ReLogic/Content/Sources/IContentSource.cs.patch [hunk 2]
```diff
@@ -54,6 +56,15 @@
 +		!Rejections.IsRejected(assetName) && GetExtension(assetName) != null;
 +
 +	// Added by TML.
-+	IEnumerable<string> GetAllAssetsStartingWith(string assetNameStart) =>
-+		EnumerateAssets().Where(s => s.StartsWith(assetNameStart));
++	[Obsolete, SuppressMessage("CodeQuality", "IDE0051:Remove unused private members")]
++	private IEnumerable<string> GetAllAssetsStartingWith(string assetNameStart)
++		=> GetAllAssetsStartingWith(assetNameStart, ignoreCase: false);
```
Comment (Chicken-Bones) [inline patches/tModLoader/ReLogic/Content/Sources/IContentSource.cs.patch:61]: Why make this private member? Are mods reflecting it?

File: patches/tModLoader/ReLogic/Content/Sources/IContentSource.cs.patch [hunk 3]
```diff
@@ -54,6 +56,15 @@
...
++
++	// Added by TML.
++	IEnumerable<string> GetAllAssetsStartingWith(string assetNameStart, bool ignoreCase = false)
++	{
++		var comparison = ignoreCase ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal;
++
++		return EnumerateAssets().Where(s => s.StartsWith(assetNameStart, comparison));
```
Comment (Chicken-Bones) [inline patches/tModLoader/ReLogic/Content/Sources/IContentSource.cs.patch:68]: Is this really the correct solution? The entire asset system in vanilla is case insensitive. Should we just be using `.ToLowerInvariant()` everywhere instead?

File: patches/tModLoader/ReLogic/Content/Sources/FileSystemContentSource.cs.patch [hunk 4]
```diff
@@ -19,13 +23,18 @@
...
  
  		BuildNameToAbsolutePathDictionary();
 +
 +		// Added by TML.
 +		SetAssetNames(_nameToAbsolutePath.Keys);
++
++		// #2617 - Allow using paths with extensions in GetExtension calls, because we happen to return such paths in EnumerateAssets().
++		foreach (var pair in assetExtensions.ToArray()) {
++			assetExtensions.TryAdd(pair.Key + pair.Value, pair.Value);
++		}
```
Comment (Chicken-Bones) [inline patches/tModLoader/ReLogic/Content/Sources/FileSystemContentSource.cs.patch:37]: Shouldn't this be in `SetAssetNames`? There are other content sources than just `FileSystemContentSource`

File: patches/tModLoader/ReLogic/Content/Sources/IContentSource.cs.patch (hunk 2 above)
Comment (Mirsario) [reply patches/tModLoader/ReLogic/Content/Sources/IContentSource.cs.patch:61]: To avoid runtime breakage from introducing a new parameter. I don't recall the protection modifier mattering in that case.

File: patches/tModLoader/ReLogic/Content/Sources/FileSystemContentSource.cs.patch (hunk 4 above)
Comment (Mirsario) [reply patches/tModLoader/ReLogic/Content/Sources/FileSystemContentSource.cs.patch:37]: FSCS is the only content source that returns paths with extensions in EnumerateAssets. I went for the most minimal solution with the least chance of breaking anything further, as this fix is intended to be cherrypicked to stable. Future asset system reworks from #1612 can make more permanent improvements.

File: patches/tModLoader/ReLogic/Content/Sources/IContentSource.cs.patch (hunk 2 above)
Comment (steviegt6) [reply patches/tModLoader/ReLogic/Content/Sources/IContentSource.cs.patch:61]: Without IgnoresAccessChecksTo, references to private members of another assembly (even if linked to public members at compile time) will be thrown; one would need to annotate their mod assembly with `[assembly: IgnoresAccessChecksTo("tModLoader")]` (or module) to avoid this. Late, but relevant.
